struct Node{
	int val;
	Node next;
}

generator Node newNode(int v){ /* automatically rewritten */
	Node n = new Node();
	n.val = v;
	n.next = null;	
	return n;
}

bit test(int in){	
	return 1;
}

bit testSK(int in) implements test{
	int global = in;
	int c = 0;
	bit[2] out = 0;
	fork(int i; 2){
		int t = i;
		bit more = 1;
		for(int j=0; j<3; ++j){
			if(more){
				c = t;
				lock(0);
				if(c == t){
					out[i] = 1;
					more = 0;	
				}
				if(t==0){
					t = 1;	
				}else{
					t = 0;
				}
				unlock(0);
			}
		}
	}
	assert  out[0] && out[1];
	return 1;
}



