struct Node{
	int val;
	Node next;
}

Node newNode(int v){
	Node n = new Node();
	n.val = v;
	n.next = null;	
	return n;
}

bit test(bit in){	
	return 1;
}

bit testSK(bit in) implements test{
	Node n = newNode(0);
	n.next = newNode(1);
	n.next.next = newNode(2);
	fork(int i; 2){
		Node l = n;
		for(int i=0; i<3; ++i){
			lock(1);
			l.val = l.val + 1;
			unlock(1);
			l = l.next;
		}
	}
	assert  n.val == 2 && n.next.val == 3 && n.next.next.val == 4;
	return 1;
}



