

struct Box {
	int val;	
}

generator Box newBox(int i){ /* automatically rewritten */
	Box b = new Box();
	b.val = i;
	return b;	
}

generator int getVal(Box b){ /* automatically rewritten */
	return b.val;	
}

int N = 2;

bit test(int in){	
	return 1;
}

bit testSK(int in) implements test{
	Box global = newBox(in);
	int out;
	fork(int i; 2){
		atomic{
		int local = global.val; //getVal(global);
		
		local = local + 1;
		out = local;
		}
			
	}
	assert out == in + 1;
	return 1;
}



