//Needs schedlen 18.

int N = 2;

bit test(int in){	
	return 1;
}

int gen(int i, int j){
	if(??){
		if(??){
			return i;
		}else{
			return j;	
		}	
	}else{		
		return gen(i,j) + ??;		
	}
	
}

bit testSK(int in) implements test{
	int global = in;
	ploop(int i; 2){
		int local;
		anyorder{
			lock(1);
			unlock(1);
			local = gen(local, global) + 1;
			global = local;	
		}
	}
	return global == in + 2;
}



