// $ANTLR 2.7.7 (2006-11-01): "StreamItParserFE.g" -> "StreamItParserFE.java"$

	package streamit.frontend;

	import streamit.frontend.nodes.*;

	import java.util.Collections;
import java.io.*;
import java.util.List;

	import java.util.ArrayList;

public interface StreamItParserFETokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_loop = 4;
	int TK_new = 5;
	int TK_boolean = 6;
	int TK_float = 7;
	int TK_bit = 8;
	int TK_int = 9;
	int TK_void = 10;
	int TK_double = 11;
	int TK_complex = 12;
	int TK_struct = 13;
	int TK_if = 14;
	int TK_else = 15;
	int TK_while = 16;
	int TK_for = 17;
	int TK_switch = 18;
	int TK_case = 19;
	int TK_default = 20;
	int TK_break = 21;
	int TK_continue = 22;
	int TK_return = 23;
	int TK_true = 24;
	int TK_false = 25;
	int TK_implements = 26;
	int TK_assert = 27;
	int INCLUDE = 28;
	int ARROW = 29;
	int WS = 30;
	int SL_COMMENT = 31;
	int ML_COMMENT = 32;
	int LPAREN = 33;
	int RPAREN = 34;
	int LCURLY = 35;
	int RCURLY = 36;
	int LSQUARE = 37;
	int RSQUARE = 38;
	int PLUS = 39;
	int PLUS_EQUALS = 40;
	int INCREMENT = 41;
	int MINUS = 42;
	int MINUS_EQUALS = 43;
	int DECREMENT = 44;
	int STAR = 45;
	int STAR_EQUALS = 46;
	int DIV = 47;
	int DIV_EQUALS = 48;
	int MOD = 49;
	int LOGIC_AND = 50;
	int LOGIC_OR = 51;
	int BITWISE_AND = 52;
	int BITWISE_OR = 53;
	int BITWISE_XOR = 54;
	int ASSIGN = 55;
	int EQUAL = 56;
	int NOT_EQUAL = 57;
	int LESS_THAN = 58;
	int LESS_EQUAL = 59;
	int MORE_THAN = 60;
	int MORE_EQUAL = 61;
	int QUESTION = 62;
	int COLON = 63;
	int SEMI = 64;
	int COMMA = 65;
	int DOT = 66;
	int BANG = 67;
	int LSHIFT = 68;
	int RSHIFT = 69;
	int NDVAL = 70;
	int NDVAL2 = 71;
	int SELECT = 72;
	int CHAR_LITERAL = 73;
	int STRING_LITERAL = 74;
	int ESC = 75;
	int DIGIT = 76;
	int HQUAN = 77;
	int NUMBER = 78;
	int ID = 79;
	int TK_pipeline = 80;
	int TK_splitjoin = 81;
	int TK_feedbackloop = 82;
	int TK_sbox = 83;
	int TK_work = 84;
	int TK_prework = 85;
	int TK_phase = 86;
	int TK_push = 87;
	int TK_pop = 88;
	int TK_peek = 89;
	int TK_init = 90;
	int TK_split = 91;
	int TK_join = 92;
	int TK_roundrobin = 93;
	int TK_duplicate = 94;
	int TK_enqueue = 95;
	int TK_portal = 96;
	int TK_handler = 97;
	int TK_do = 98;
	int TK_pi = 99;
}
