// $ANTLR 2.7.5 (20050128): "StreamItParserFE.g" -> "StreamItParserFE.java"$

	package streamit.frontend;

	import streamit.frontend.nodes.*;

	import java.util.Collections;
import java.io.*;
import java.util.List;

	import java.util.ArrayList;

public interface StreamItParserFETokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_filter = 4;
	int TK_pipeline = 5;
	int TK_splitjoin = 6;
	int TK_sbox = 7;
	int TK_feedbackloop = 8;
	int TK_portal = 9;
	int TK_to = 10;
	int TK_handler = 11;
	int TK_add = 12;
	int TK_split = 13;
	int TK_join = 14;
	int TK_duplicate = 15;
	int TK_roundrobin = 16;
	int TK_body = 17;
	int TK_loop = 18;
	int TK_enqueue = 19;
	int TK_init = 20;
	int TK_prework = 21;
	int TK_work = 22;
	int TK_phase = 23;
	int TK_peek = 24;
	int TK_pop = 25;
	int TK_push = 26;
	int TK_boolean = 27;
	int TK_float = 28;
	int TK_bit = 29;
	int TK_int = 30;
	int TK_void = 31;
	int TK_double = 32;
	int TK_complex = 33;
	int TK_struct = 34;
	int TK_template = 35;
	int TK_if = 36;
	int TK_else = 37;
	int TK_while = 38;
	int TK_for = 39;
	int TK_switch = 40;
	int TK_case = 41;
	int TK_default = 42;
	int TK_break = 43;
	int TK_continue = 44;
	int TK_return = 45;
	int TK_pi = 46;
	int TK_true = 47;
	int TK_false = 48;
	int TK_implements = 49;
	int TK_overrides = 50;
	int TK_assert = 51;
	int INCLUDE = 52;
	int ARROW = 53;
	int WS = 54;
	int SL_COMMENT = 55;
	int ML_COMMENT = 56;
	int LPAREN = 57;
	int RPAREN = 58;
	int LCURLY = 59;
	int RCURLY = 60;
	int LSQUARE = 61;
	int RSQUARE = 62;
	int PLUS = 63;
	int PLUS_EQUALS = 64;
	int INCREMENT = 65;
	int MINUS = 66;
	int MINUS_EQUALS = 67;
	int DECREMENT = 68;
	int STAR = 69;
	int STAR_EQUALS = 70;
	int DIV = 71;
	int DIV_EQUALS = 72;
	int MOD = 73;
	int LOGIC_AND = 74;
	int LOGIC_OR = 75;
	int BITWISE_AND = 76;
	int BITWISE_OR = 77;
	int BITWISE_XOR = 78;
	int ASSIGN = 79;
	int EQUAL = 80;
	int NOT_EQUAL = 81;
	int LESS_THAN = 82;
	int LESS_EQUAL = 83;
	int MORE_THAN = 84;
	int MORE_EQUAL = 85;
	int QUESTION = 86;
	int COLON = 87;
	int SEMI = 88;
	int COMMA = 89;
	int DOT = 90;
	int BANG = 91;
	int LSHIFT = 92;
	int RSHIFT = 93;
	int NDVAL = 94;
	int NDVAL2 = 95;
	int SELECT = 96;
	int CHAR_LITERAL = 97;
	int STRING_LITERAL = 98;
	int ESC = 99;
	int DIGIT = 100;
	int HQUAN = 101;
	int NUMBER = 102;
	int ID = 103;
	int TK_do = 104;
}
