#!/bin/bash
echo "Building frontend..."
javac -classpath antlr.jar:. -d bin "$@" streamit/frontend/ToSBit.java
if [[ -f streamit/frontend/ToStencilSK.java ]]; then
  javac -classpath antlr.jar:. -d bin "$@" streamit/frontend/ToStencilSK.java
fi
echo "...done"
