{\rtf1\ansi\ansicpg1251\cocoartf2761
\cocoatextscaling0\cocoaplatform0{\fonttbl\f0\fnil\fcharset0 .AppleSystemUIFontMonospaced-Regular;}
{\colortbl;\red255\green255\blue255;\red236\green244\blue251;\red17\green21\blue26;}
{\*\expandedcolortbl;;\cssrgb\c94118\c96471\c98824;\cssrgb\c8235\c10588\c13725;}
\margl1440\margr1440\vieww12540\viewh16140\viewkind1
\deftab720
\pard\pardeftab720\partightenfactor0

\f0\fs27\fsmilli13600 \cf2 \cb3 \expnd0\expndtw0\kerning0
\outl0\strokewidth0 \strokec2 bit op(bit x0, bit x1) \{\
    return \{| !(x0 && x1) | !(x0 || x1) |\};\
\}\
@FromFile("bits.data")\
harness void sketch_main(int n, bit[n] bits, bit out) \{\
    assert(op(bits[??], bits[??]) == out);\
\}\
}