int N;
float[N][N] sten14(float[N][N]  in, int a){
   float[N][N] out=0;
   for(int i=a; i<N; ++i){
     for(int j=a; j<N; ++j){
      out[i][j] = in[i][j];
     }
   }
   return out; 
}


float[N][N] stenSK14(float[N][N]  in, int a) implements sten14{
   float[N][N] out=0;
   float[N+1][N+1] t;
   for(int i=a; i<N; ++i){
	 t[i][a] = in[i][a];
     for(int j=a; j<N; ++j){
      out[i][j] = t[i][j];
      t[i][j+??] = in[i][j+??];
     }
   }
   return out; 
}
