#!/bin/bash

# Set classpath, solver path, and source path; adjust for Cygwin as necessary
[ $OSTYPE == "cygwin" ] && { sep="\\"; pathsep=";"; } ||
{ sep="/"; pathsep=":"; }

TMPCLASSPATH="${FRONTEND}${sep}antlr.jar${pathsep}${FRONTEND}${sep}bin${pathsep}."
TMPSBITPATH="${SOLVER}${sep}"
TMPSOURCEPATH=$(dirname $(dirname "$0"))

# warn the user if certain environment variables should be set
if [ -z "$FRONTEND" ] || ! [ -f "${FRONTEND}${sep}antlr.jar" ]; then
    echo "WARNING - consider exporting \$FRONTEND" 1>&2
fi
if [ -z "$SOLVER" ] || ! [ -f "${SOLVER}${sep}SBitII" ]; then
    echo "WARNING - consider exporting \$SOLVER" 1>&2
fi

# Get the last command-line argument as INFILE
#
ARGS=
LASTARG=

for INFILE; do
	ARGS="${ARGS} ${LASTARG}";
	LASTARG="$INFILE";
done

CPPTEMP="${INFILE}.cpp"
ARGS="${ARGS} ${INFILE}"

# Launch
#
java -ea \
  -classpath "$TMPCLASSPATH" \
  streamit.frontend.ToSBit --output "${INFILE}.tmp" \
  --sbitpath "$TMPSBITPATH" $ARGS
