pragma options "--bnd-cbits 3 --bnd-inbits 4 --bnd-branch-amnt 10 --bnd-inline-amnt 4 --bnd-unroll-amnt 4  ";

int N;

float[2*N][2*N][2*N] MGinter(float[N][N][N] in){

	float[2*N][2*N][2*N]  output=0;
	for(int k=0; k<2*N-2; ++k){
		for(int j=0; j<2*N-2; ++j){
		for(int i=0; i<2*N-2; ++i){
		 if( i%2==0 && j%2==0 && k%2==0) output[i][j][k] = in[i/2][j/2][k/2];
		 
		 if( i%2==1 && j%2==0 && k%2==0) output[i][j][k] = 
		 									0.5 * (in[i/2][j/2][k/2] + in[i/2+1][j/2][k/2]);
		 if( i%2==0 && j%2==1 && k%2==0) output[i][j][k] = 
		 									0.5 * (in[i/2][j/2][k/2] + in[i/2][j/2+1][k/2]);
		 if( i%2==0 && j%2==0 && k%2==1) output[i][j][k] = 
		 									0.5 * (in[i/2][j/2][k/2] + in[i/2][j/2][k/2+1]);
		 
		 if( i%2==1 && j%2==1 && k%2==0) output[i][j][k] = 
		 									0.25 * 
		 									(in[i/2][j/2][k/2] + in[i/2+1][j/2+1][k/2] +
		 										in[i/2][j/2+1][k/2] + in[i/2+1][j/2][k/2]);
		 if( i%2==0 && j%2==1 && k%2==1) output[i][j][k] = 
		 									0.25 * 
		 									(in[i/2][j/2][k/2] + in[i/2][j/2+1][k/2+1] +
		 										in[i/2][j/2+1][k/2] + in[i/2][j/2][k/2+1]
		 									);
		 									
		 if( i%2==1 && j%2==0 && k%2==1) output[i][j][k] = 
		 									0.25 * 
		 									(in[i/2][j/2][k/2] + in[i/2+1][j/2][k/2+1] +
		 										in[i/2+1][j/2][k/2] + in[i/2][j/2][k/2+1]
		 									);
		 if( i%2==1 && j%2==1 && k%2==1) output[i][j][k] = 
		 									0.125 * 
		 									(in[i/2][j/2][k/2] + in[i/2+1][j/2][k/2] +
		 										in[i/2][j/2+1][k/2] + in[i/2][j/2][k/2+1] +
		 										in[i/2+1][j/2+1][k/2] + in[i/2][j/2+1][k/2+1] +
		 										in[i/2+1][j/2][k/2+1] + in[i/2+1][j/2+1][k/2+1]
		 									);
		}
		}
	}
	return output;
}







float[2*N][2*N][2*N] skMGinter(float[N][N][N] in)implements MGinter
{

	float[2*N][2*N][2*N]  output=0;
	for(int i=??; i<(N-2)+??; ++i){
		for(int j=??; j<(N-2)+??; ++j){
			for(int k=??; k<(N-2)+??; ++k){
				output[k*2+??][j*2+??][i*2+??] = in[k+??][j+??][i+??]; //
				output[k*2+??][j*2+??][i*2+??] = 0.5 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] );
				output[k*2+??][j*2+??][i*2+??] = 0.5 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] );
				output[k*2+??][j*2+??][i*2+??] = 0.5 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] );
				
				output[k*2+??][j*2+??][i*2+??] = 0.25 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??]);
				output[k*2+??][j*2+??][i*2+??] = 0.25 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??]);
				output[k*2+??][j*2+??][i*2+??] = 0.25 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??]);				

				output[k*2+??][j*2+??][i*2+??] = 0.125 * ( in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] 
				                                  + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??] + in[k+??][j+??][i+??]);				
			}						
		}
	}
	return output;
}





