// $ANTLR 2.7.7 (20060906): "src/main/other/sketch/compiler/parser/StreamItParserFE.g" -> "StreamItParserFE.java"$

package sketch.compiler.parser;

import java.io.DataInputStream;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.Map;
import java.util.HashMap;

import sketch.compiler.Directive;
import sketch.compiler.ast.core.FEContext;
import sketch.compiler.ast.core.FieldDecl;
import sketch.compiler.ast.core.Function;
import sketch.compiler.ast.core.Parameter;
import sketch.compiler.ast.core.Program;
import sketch.compiler.ast.core.Annotation;
import sketch.compiler.ast.core.NameResolver;
import sketch.util.datastructures.HashmapList;
import sketch.compiler.ast.core.exprs.ExprStar.Kind;

import sketch.compiler.ast.core.Package;


import sketch.compiler.ast.core.exprs.*;
import sketch.compiler.ast.core.exprs.regens.*;
import sketch.compiler.ast.core.stmts.*;
import sketch.compiler.ast.core.typs.*;
import sketch.compiler.ast.cuda.exprs.*;
import sketch.compiler.ast.cuda.stmts.*;
import sketch.compiler.ast.cuda.typs.*;

import sketch.compiler.ast.promela.stmts.StmtFork;
import sketch.compiler.main.cmdline.SketchOptions;

import sketch.compiler.ast.spmd.stmts.StmtSpmdfork;

import static sketch.util.DebugOut.assertFalse;

public interface StreamItParserFETokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_atomic = 4;
	int TK_fork = 5;
	int TK_insert = 6;
	int TK_into = 7;
	int TK_loop = 8;
	int TK_repeat = 9;
	int TK_minrepeat = 10;
	int TK_new = 11;
	int TK_null = 12;
	int TK_reorder = 13;
	int TK_assume = 14;
	int TK_boolean = 15;
	int TK_float = 16;
	int TK_bit = 17;
	int TK_int = 18;
	int TK_void = 19;
	int TK_double = 20;
	int TK_fun = 21;
	int TK_char = 22;
	int TK_struct = 23;
	int TK_ref = 24;
	int TK_adt = 25;
	int TK_if = 26;
	int TK_else = 27;
	int TK_while = 28;
	int TK_for = 29;
	int TK_switch = 30;
	int TK_case = 31;
	int TK_repeat_case = 32;
	int TK_default = 33;
	int TK_break = 34;
	int TK_do = 35;
	int TK_continue = 36;
	int TK_return = 37;
	int TK_true = 38;
	int TK_false = 39;
	int TK_parfor = 40;
	int TK_until = 41;
	int TK_by = 42;
	int TK_implements = 43;
	int TK_assert = 44;
	int TK_assert_max = 45;
	int TK_h_assert = 46;
	int TK_generator = 47;
	int TK_harness = 48;
	int TK_model = 49;
	int TK_global = 50;
	int TK_serial = 51;
	int TK_spmdfork = 52;
	int TK_stencil = 53;
	int TK_include = 54;
	int TK_pragma = 55;
	int TK_package = 56;
	int TK_extends = 57;
	int ARROW = 58;
	int LARROW = 59;
	int WS = 60;
	int LINERESET = 61;
	int SL_COMMENT = 62;
	int ML_COMMENT = 63;
	int LPAREN = 64;
	int RPAREN = 65;
	int LCURLY = 66;
	int RCURLY = 67;
	int LSQUARE = 68;
	int RSQUARE = 69;
	int PLUS = 70;
	int PLUS_EQUALS = 71;
	int INCREMENT = 72;
	int MINUS = 73;
	int MINUS_EQUALS = 74;
	int DECREMENT = 75;
	int STAR = 76;
	int STAR_EQUALS = 77;
	int DIV = 78;
	int DIV_EQUALS = 79;
	int MOD = 80;
	int LOGIC_AND = 81;
	int LOGIC_OR = 82;
	int BITWISE_AND = 83;
	int BITWISE_OR = 84;
	int BITWISE_XOR = 85;
	int ASSIGN = 86;
	int DEF_ASSIGN = 87;
	int TRIPLE_EQUAL = 88;
	int EQUAL = 89;
	int NOT_EQUAL = 90;
	int LESS_THAN = 91;
	int LESS_EQUAL = 92;
	int MORE_THAN = 93;
	int MORE_EQUAL = 94;
	int QUESTION = 95;
	int COLON = 96;
	int SEMI = 97;
	int COMMA = 98;
	int DOT = 99;
	int BANG = 100;
	int LSHIFT = 101;
	int RSHIFT = 102;
	int NDVAL = 103;
	int NDVAL2 = 104;
	int SELECT = 105;
	int NDANGELIC = 106;
	int AT = 107;
	int BACKSLASH = 108;
	int LESS_COLON = 109;
	int DOLLAR = 110;
	int REGEN = 111;
	int CHAR_LITERAL = 112;
	int STRING_LITERAL = 113;
	int ESC = 114;
	int DIGIT = 115;
	int HQUAN = 116;
	int NUMBER = 117;
	int ID = 118;
	int TK_device = 119;
	int TK_library = 120;
	int TK_printfcn = 121;
}
