// $ANTLR 2.7.7 (2006-11-01): "StreamItParserFE.g" -> "StreamItParserFE.java"$

	package streamit.frontend.parser;

	import streamit.frontend.nodes.*;

	import java.util.Collections;
import java.io.*;
import java.util.List;

	import java.util.ArrayList;

public interface StreamItParserFETokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_atomic = 4;
	int TK_fork = 5;
	int TK_insert = 6;
	int TK_into = 7;
	int TK_loop = 8;
	int TK_new = 9;
	int TK_null = 10;
	int TK_reorder = 11;
	int TK_boolean = 12;
	int TK_float = 13;
	int TK_bit = 14;
	int TK_int = 15;
	int TK_void = 16;
	int TK_double = 17;
	int TK_complex = 18;
	int TK_struct = 19;
	int TK_ref = 20;
	int TK_if = 21;
	int TK_else = 22;
	int TK_while = 23;
	int TK_for = 24;
	int TK_switch = 25;
	int TK_case = 26;
	int TK_default = 27;
	int TK_break = 28;
	int TK_continue = 29;
	int TK_return = 30;
	int TK_true = 31;
	int TK_false = 32;
	int TK_implements = 33;
	int TK_assert = 34;
	int TK_static = 35;
	int INCLUDE = 36;
	int ARROW = 37;
	int WS = 38;
	int SL_COMMENT = 39;
	int ML_COMMENT = 40;
	int LPAREN = 41;
	int RPAREN = 42;
	int LCURLY = 43;
	int RCURLY = 44;
	int LSQUARE = 45;
	int RSQUARE = 46;
	int PLUS = 47;
	int PLUS_EQUALS = 48;
	int INCREMENT = 49;
	int MINUS = 50;
	int MINUS_EQUALS = 51;
	int DECREMENT = 52;
	int STAR = 53;
	int STAR_EQUALS = 54;
	int DIV = 55;
	int DIV_EQUALS = 56;
	int MOD = 57;
	int LOGIC_AND = 58;
	int LOGIC_OR = 59;
	int BITWISE_AND = 60;
	int BITWISE_OR = 61;
	int BITWISE_XOR = 62;
	int ASSIGN = 63;
	int EQUAL = 64;
	int NOT_EQUAL = 65;
	int LESS_THAN = 66;
	int LESS_EQUAL = 67;
	int MORE_THAN = 68;
	int MORE_EQUAL = 69;
	int QUESTION = 70;
	int COLON = 71;
	int SEMI = 72;
	int COMMA = 73;
	int DOT = 74;
	int BANG = 75;
	int LSHIFT = 76;
	int RSHIFT = 77;
	int NDVAL = 78;
	int NDVAL2 = 79;
	int SELECT = 80;
	int REGEN = 81;
	int CHAR_LITERAL = 82;
	int STRING_LITERAL = 83;
	int ESC = 84;
	int DIGIT = 85;
	int HQUAN = 86;
	int NUMBER = 87;
	int ID = 88;
	int TK_pipeline = 89;
	int TK_splitjoin = 90;
	int TK_feedbackloop = 91;
	int TK_sbox = 92;
	int TK_work = 93;
	int TK_prework = 94;
	int TK_phase = 95;
	int TK_push = 96;
	int TK_pop = 97;
	int TK_peek = 98;
	int TK_init = 99;
	int TK_split = 100;
	int TK_join = 101;
	int TK_roundrobin = 102;
	int TK_duplicate = 103;
	int TK_enqueue = 104;
	int TK_portal = 105;
	int TK_handler = 106;
	int TK_do = 107;
	int TK_pi = 108;
}
