#!/bin/bash

scriptname="$(readlink -f "$0")"
dirname="$(dirname "$scriptname")"
jarname="$dirname/sketch-${version}-all-${osname}-${osarch}.jar"

function err() {
    echo "ERROR running bash script '$scriptname'" >&2
    echo "$1" >&2
    exit 1
}

if [ -z "$(java -version 2>&1 | grep 1.6)" ]; then
    err "please configure \$PATH so you are using Java 1.6"
fi
if ! [ -f "$jarname" ]; then
    err "couldn't find file '$jarname'"
fi
java -cp "$jarname" -ea sketch.compiler.main.seq.SequentialSketchMain "$@"
