pragma options "--bnd-cbits 2 --bnd-inbits 2 --bnd-intbits 32 --bnd-inline-amnt 1000 --bnd-unroll-amnt 20";

int main(int dummy) implements one{
	
//	assert fib(3) == 2;
	assert fib(4) == 3;
//	assert fib(5) == 5;
	return 1;
}

int one(int dummy) {
	return 1;
}

int fib(int n) { /* automatically rewritten */
	if (n == 0)
		return 0;
	else if (n == 1)
		return ??;
	else
		return fib(n-1) + fib(n-2);

}

