/*
 * triggers a bug in frontend
 */
pragma options "-p preproc --bnd-inbits 3 --bnd-cbits 4 --bnd-unroll-amnt 16 --bnd-inline-amnt 3 --beopt:-bndwrand 50  --bnd-arr-size 16 --be:ufunSymmetry  --beopt:simplifycex NOSIM --beopt:simiters 3"; //  --be:showDAG

void movein(ref int x) {
	x = x * ??;
}

stencil void spec(int N, ref int[N] a) {
	if (N>1) {
		a[0] = a[0]+a[0];
	}
}

stencil void sk(int N, ref int[N] a) implements spec {
	if (N>1) {
		movein(a[??]);
	}
}