//Struct representing a parent cannot be instantiated - nested ADT
struct ASTNode{ int type; }
struct Expression extends ASTNode{  }
struct Statement extends ASTNode{  }
struct Plus extends Expression{ Expression left; Expression right; }
struct Times extends Expression{ Expression left; Expression right; }
struct IfStmt extends Statement{ Expression cond; Statement tpart; Statement epart; }
struct WhileStmt extends Statement{ Expression cond; Statement body;  } // nested adt



harness void test(){
	Expression expr = new Expression(); // TypeError

}
