//Struct type casting error
//Tests for ADT
struct Tree{ 
	int x;
	
}


struct Leaf extends Tree{
    int value;
}
struct Branch extends Tree{
    Tree left;
    Tree right;
}


harness void test(){	

Branch branch = new Branch();
branch.left = new Leaf();
Branch b = (Branch) sum(branch); // TypeError

}

Tree sum(Tree t){	
    
    switch(t){
        case Leaf: 
            /* t is now of type Leaf in this branch */
            {
                        return t;
            }                     
      
            
        case Branch:
			{
            /* t is of type Branch in this branch */
            if(t.left!=null){
            return t.left;
            }else{
            	return t;
            }
		}
    }
}