//Parse failed
struct Tree{ 
}


struct Leaf extends Tree{
    int value;
}
struct Branch extends Tree{
    Tree left;
    Tree right;
}


harness void test(){
	Leaf leaf1 = new Leaf(value = 5);

	
Leaf leaf2 = new Leaf(value = 4);

Branch branch = new Branch();
branch.left = leaf1;
branch.right = leaf2;


int x =   sum(branch);

}

int sum(Tree t){
	
    switch(t){
    	//statements other than cases cannot be in switch block
    	int x; // TypeError
        case Leaf: // TypeError
            /* t is now of type Leaf in this branch */
            {
                        return t.value;
            }                     
      
            
        case Branch:
			{
            /* t is of type Branch in this branch */
            return sum(t.left) + sum(t.right);
		}
    }
    /* Outside the switch, t goes back to being of type Tree*/
}