int N;
bit[N][N] sten(bit[N][N]  in, int a){
   bit[N][N] out=0;
   for(int i=a; i<N; ++i){
     for(int j=a; j<N; ++j){
      out[i][j] = in[i][j];
     }
   }
   return out; 
}


bit[N][N] stenSK(bit[N][N]  in, int a) implements sten{
   bit[N][N] out=0;
   
   for(int i=a; i<N; ++i){
	bit t = in[i][a];
     for(int j=a; j<N; ++j){
      out[i][j] = t;
      t = in[i][j+??];
     }
   }
   return out; 
}