int N;
int[N] test16(int[N] in){
  int[N] out;
  for(int i=0; i<N; ++i){
  	if(i>0 && i<N-1) out[i] = in[i-1] + in[i+1];
  	else out[i] = 0;
  }
  return out;
}


int[N] testSK16(int[N] in) implements test16 {
  int[N] out = 0;
  if( N>= 4){
	  out[1] = in[0];
	  out[2] = in[1];
	  for(int i=??; i<N-??; ++i){  	
	  	out[i-1] += in[i];
	  	out[i+1] = in[i];
	  }
	  out[N-??] += in[N-??];
	  out[N-??] += in[N-??];
  }else{
	  for(int i=??; i<N-??; ++i){
	  	 out[i] = in[i-1] + in[i+1];
	  }
  }
  return out;
}
