pragma options "--bnd-unroll-amnt 30 --bnd-inbits 3";

int x = 0;

int[x] arr(int x, int[x] t){
    int[x] out;
    for(int i=0; i<x; ++i){
        out[i] = x;
    }
    return out;
}

harness void main(int y){
    x = 27;
    int t = x;
    int[t] b=0;
    b = arr(x, b);
    for(int i=0; i<27; ++i){
        assert b[i] == 27;
    }
    x = y;
    int u = x;
    int[u] c=0;
    c = arr(x, c);
    for(int i=0; i<y; ++i){
        assert c[i] == y;
    }
}
