//Correct
struct Tree{ 
	int x;
}


struct Leaf extends Tree{
    int value;
}
struct Branch extends Tree{
    Tree left;
    Tree right;
}


harness void test(){	

Branch branch = new Branch();
Branch b = (Branch) sum(branch);

}

Tree sum(Tree t){	
    
    switch(t){
        case Leaf: 
            /* t is now of type Leaf in this branch */
            {
                        return t;
            }                     
      
            
        case Branch:
			{
            /* t is of type Branch in this branch */
            return t;
		}
    }
}