pragma options "--bnd-inbits 3";


stencil int[N] test0(int N, int[N] in){
  int[N] out;
  for(int i=0; i<N-3; ++i){
    out[i] = in[i+3];
  }
  return out;
}

generator void foo(fun body, int N, int[N] in, ref int[N] out){
    for(int i=0; i<N-??; ++i){
        body(i);
      }
}

stencil int[N] testSK0(int N, int[N] in) implements test0 {
  int[N] out;
  generator void temp(int i){ out[i] = in[i+??]; }
  foo(temp, N, in, out);
  return out;
}

    
