
int foo(int x);
harness void main(){ 
int I0 = 4; 
int[15]  A0;
int I1 = 12;
int[24]  A1;
int I2 = 1; 
int[10]  A2;
int I3 = 9;
int[4/*??*/]  A3;
A3[2/*(??)*/] = A1[((0)?A2[I1]:(7))];
I1 = I3;
I1 = I0;
A2[((I2*A2[I2])*A3[I2])] = (I1-((((((I1-(??/*repl with 3*/))+foo(foo(??)))-I0)-A1[(??)])-A1[((7)-(??))])/I1));
I2 = (??);
I1 = A2[A1[(7)]];
I3 = A0[(foo(A1[(I1*A2[A0[(??)]])])/(!(((??)&&(1)))?(8):I2))];
}