int W = 5;

generator int poly(bit[W] n, bit[W] x) { /* automatically rewritten */			
	if (!n[0]&!n[1]&!n[2]&!n[3]&!n[4]) return ??; 
	else return ??;
}


bit spec (bit[W] x) {
	return x[2];
}


bit p1Sk (bit[W] x) implements spec {
	bit[W] one = 0; one[0] = 1;
	bit[W] two = 0; two[1] = 1;
	bit[W] three = one+two;
	bit[W] four = two+two;
	bit[W] five = four+one;
	int idx = poly(five,x);
	return x[idx];
}

