
pragma options "--bnd-inbits 3 --beopt:simiters 3";


int Oplus= 0;
int Ominus=1;
int Oneg = 2;
int Oand = 3;
int Oor = 4;
int Onot = 5;
int Ogt = 6;
int Olt = 7;

int size = 5;
struct sourceAST {@Immutable("")}
struct SNum extends sourceAST{int val;}
struct SVar extends sourceAST{ int str;}
struct STrue extends sourceAST{}
struct SFalse extends sourceAST{}
struct SAssign extends sourceAST{int str; sourceAST a;}
struct SLet extends sourceAST{int str; sourceAST a; sourceAST b;}
struct SPrim1 extends sourceAST{int op; sourceAST a;}
struct SPrim2 extends sourceAST{int op; sourceAST a; sourceAST b;}
struct SBetween extends sourceAST{sourceAST a;sourceAST b;sourceAST c;}

struct SIf extends sourceAST{sourceAST a; sourceAST b; sourceAST c;}




//CoreAST

struct coreAST{@Immutable("")}
struct CPrim2 extends coreAST{int op; coreAST a; coreAST b;}
struct CNum extends coreAST{int val;}
struct CVar extends coreAST{int str;}
struct CBool extends coreAST{bit val;}
struct CIf extends coreAST{coreAST a; coreAST b; coreAST c;}
struct CPrim1 extends coreAST{int op; coreAST a;}

struct CAssign extends coreAST{int str; coreAST a;}
struct CLet extends coreAST{int str; coreAST a; coreAST b;}





coreAST desugar(sourceAST s, int bnd2){
	if(s == null){ return null; }
	if(bnd2 <= 0 ){ return null; }
		
	generator int getOp(int op){ return {| op |Oplus | Ominus | Oneg | Oand | Oor | Onot | Ogt | Olt |}; }  
	generator int getStr(){ return ??(3); }
	generator int getConst(int c){return {| c|??|};}
	
	//generator for coreAST
	generator coreAST getPart(coreAST c1, coreAST c2, coreAST c3, int bnd, int depth) {
		//assert bnd > 0;
		if(bnd<1) return null;
		
		coreAST var = new CVar(str=getStr());
		//coreAST c4 = new CPrim2(op = Oand, a = new CPrim2(op = Olt, a  = c3, b = new CVar(str = 1)), b = new CPrim2(op = Olt,a = new CVar(str = 1), b =  c2));
		//int t = ??;
		if(  ??||depth < 8 || bnd <=1){
			return {| c1|c2|c3|var |};
		}
		else{
			if(bnd > 1){
				//assert false;
				coreAST a = getPart(c1,c2,c3, bnd-1,depth/2);
				coreAST b = getPart(c1,c2,c3, bnd-1,depth/2);
				coreAST c = getPart(c1,c2,c3, bnd-1,depth/2);
				
				//return new CPrim2(op = getOp(1), a = a, b = b);
				return 	new ??(op=getOp(1), a = a, b =b, c= c,str = getStr(), val = getConst(1),val=??);
				
			}
		}
		return null;
	}
	generator coreAST[3] run([int n], sourceAST[n] fields){
		coreAST[3] out;
		int i=0;
		repeat(n){
		/*for(int j = 0; j< size; j++){
			smtStore[j] = null;
		}*/
			//sourceAST c1 = interpretSourceAST(fields[i],0,bnd2-2);
			
			out[i] = desugar(fields[i],bnd2-1); ++i;
			/*if(c1!=null){
				for(int j = 0; j < size; j++){
					cmtStore[j] = null;
				}
				coreAST c3 = interpretCoreAST(out[i-1],0,bnd2-1,bnd2-1);
				assert(c3!=null);
				assert(equals(c1,c3));
			}*/
		}
		return out;
	} 
	switch(s){
		case SNum: return new CNum(val = s.val);
		case STrue: return new CBool(val =1);
		case SFalse: return new CBool(val =0);
		case SVar: return new CVar(str =s.str);
		case SAssign: return new CAssign(str = s.str, a = desugar(s.a,bnd2-1));
		case SLet: return new CLet(str = s.str, a = desugar(s.a,bnd2-1), b= desugar(s.b,bnd2-1));
		case SPrim1: return new CPrim1(op = s.op, a = desugar(s.a,bnd2-1));
		case SPrim2 : return new CPrim2(op = s.op ,a = desugar(s.a,bnd2-1), b=desugar(s.b,bnd2-1));
		case SBetween:{ coreAST c = desugar(s.b, bnd2-1); return new CPrim2(op = Oand, a = new CPrim2(op = Olt, a = desugar(s.a,bnd2-1), b = c), b = new CPrim2(op = Olt, a = c, b = desugar(s.c, bnd2-1)));}
		//case SBetween: return new CLet( str = 0, a = desugar(s.b, bnd2-1), b=new CPrim2(op = Oand, a = new CPrim2(op = Olt, a = desugar(s.a,bnd2-1), b = new CVar(str = 0)), b = new CPrim2(op = Olt, a = new CVar(str = 0), b = desugar(s.c,bnd2-1))));
		case SIf: return new CIf(a = desugar(s.a,bnd2-1) , b= desugar(s.b,bnd2-1) , c =desugar(s.c,bnd2-1));
	
		/*repeat_case:
		{
			coreAST[3] v = run( s.{sourceAST} );
			//int d,d1,d2,d3;
			int d1 = ??(1);
			int d2 = ??(5);
			int d3 = ??(1);
			coreAST a = getPart(v[0], v[1], v[2], 1,d1);
			coreAST b = getPart(v[0], v[1], v[2], 3,d2);
			coreAST c = getPart(v[0], v[1], v[2], 1,d3);
			//d = d1+d2+d3;
			//minimize(d);
			int[1] op = s.{int};
			int t = ??(3);
			if (t == 0) return new CNum(val = getConst(op[0]));
			if(t==1) return new CBool(val = ??);
			if(t==2) return new CVar(str = getConst(op[0]));
			if(t==3) return new CPrim1(op = getOp(op[0]), a = a);
			if(t==4) return new CPrim2(op = getOp(op[0]),a =a ,b=b);
			if(t==5) return new CIf(a=a,b=b,c=c);
			if(t==6) return new CAssign(str = getConst(op[0]), a = a);
			if(t==7) return new CLet(str = getConst(op[0]),a =a, b=b);
			
			//return new ??(op=getOp(op[0]), a = a, b = b, c =c, str = getConst(op[0]), val = getConst(op[0]),val=??);	
		}*/
	}
}
sourceAST gBetween(sourceAST a, sourceAST b, sourceAST c){
	return new SBetween(a =a, b=b, c= c);
}
sourceAST gIf(sourceAST cond, sourceAST th, sourceAST el){
	return new SIf(a=cond, b=th, c=el);
}
sourceAST gOp([int n], int op, sourceAST[n] p){
	if(n==1){
		return new SPrim1( op= op, a = p[0]);
	}else{
		return new SPrim2(op=op, a=p[0], b=p[1]);
	}
} 

sourceAST gN(int n){
	return new SNum( val=n);
}

sourceAST gTrue(){
	return new STrue();
}
sourceAST gFalse(){
	return new SFalse();
}

coreAST cIf(coreAST cond, coreAST th, coreAST el){
	return new CIf( a=cond, b=th, c=el);
}


coreAST cOp([int n], int op, coreAST[n] p){
	if(n==1){
		return new CPrim1( op= op, a = p[0]);
	}else{
		return new CPrim2( op=op, a=p[0], b=p[1]);
	}
} 

coreAST cN(int n){
	return new CNum( val=n);
}
coreAST cLet(int str, coreAST a, coreAST b){
	return new CLet(str= str, a= a, b= b);
}
coreAST cVar(int str){
	return new CVar(str= str);
}

coreAST cBool(bit val){
	return new CBool(val = val);
}

sourceAST produce( int[50] encoding, ref int idx, int bnd, int sbnd){
	
	if(bnd <=0 || sbnd/2 == 0 ){ 
        if(encoding[idx]==0){ ++idx; return new SNum(val=encoding[idx++]); }
       if(encoding[idx]==1){++idx; return new SVar(str = encoding[idx++]);}
        if(encoding[idx]==2){ ++idx; return new STrue(); }else{ ++idx; return new SFalse(); }          
     }
    
  	if( encoding[idx]==0){ ++idx; return new SNum(val=encoding[idx++]); }
    else
     if(encoding[idx]==1){ ++idx; return new SVar(str=encoding[idx++]); }
    else
    if(encoding[idx]==2){ ++idx; return new STrue(); }
    else
    if(encoding[idx]==3){++idx; return new SFalse(); }
   
   else
     if(encoding[idx]==4){
        ++idx;
        return gOp(2, encoding[idx++],{ produce(encoding, idx, bnd-1,sbnd/2),produce(encoding, idx, bnd-1,sbnd/2)}); 
        
        
    }else
    if(encoding[idx]==5){
    	++idx;
    	return gBetween(produce(encoding, idx, bnd-1,sbnd/2), produce(encoding, idx, bnd-1,sbnd/2), produce(encoding, idx, bnd-1,sbnd/2)); 
        
    }/*else
    if (encoding[idx] <= 7 ){
    	return null;
    }*/
    else
    if(encoding[idx]==6){
    	++idx;
    	 //return gOp(1, encoding[idx++],{ produce(encoding, idx, bnd-1,sbnd/2)}); 
    	return new SAssign(str = encoding[idx++],a= produce(encoding, idx, bnd-1,sbnd/2)); 
        
    }else
  if(encoding[idx]==7){
    	++idx;
    	
    	return new SLet(str = encoding[idx++],a= produce(encoding, idx, bnd-1,sbnd/2),b = produce(encoding, idx, bnd-1,sbnd/2)); 
        
    }/*else
    if(encoding[idx]<=15){
    	return null;
    } */
    else
    if(encoding[idx]==8){
        ++idx;
        return gIf(produce(encoding, idx, bnd-1,sbnd/2), produce(encoding, idx, bnd-1,sbnd/2), produce(encoding, idx, bnd-1,sbnd/2));
    }else
   if(encoding[idx] == 9){
        ++idx;
        return gBetween(produce(encoding, idx, bnd-1,sbnd/2), produce(encoding, idx, bnd-1,sbnd/2), produce(encoding, idx, bnd-1,sbnd/2)); 
    } else{
    	return null;
    }
}


sourceAST[size] smtStore;
sourceAST interpretSourceAST(sourceAST s, ref int idx, int bnd){
	//assert(bnd >0);
	if(s==null){
		return null;
	}
	if(bnd<0 ){
		return null;
	}
	switch(s){
		case SVar:
		{
		
			if (s.str >= idx) return s;
			sourceAST val = smtStore[s.str];
				
				if (val == null) return s;
				switch(val){
					case SNum: return val;
					case STrue: return val;
					case SFalse: return val;
					case SVar: return val;
					default: return null;
				
				}
				 
			
		
		}
		case SAssign:
		{
			if(bnd <1 ) return null;
			else{
			
			sourceAST s_a = interpretSourceAST(s.a, idx,  bnd-1);
			if(s.str<0 || s.str>= size) return null;
			if (idx <= s.str) idx = s.str+1;
			
			smtStore[s.str] = s_a;
			return s_a;
			
			}
		}
		case SPrim1:
		{
			if(bnd <1 ) return null;
			else{
			if(s.op == Oneg){
				sourceAST s_a = interpretSourceAST(s.a,idx, bnd -1);
				if(s_a==null) return null;
				switch(s_a){
					case SNum: {return new SNum(val = (0-s_a.val));}
					default: {return null;}
				}
			}else
			if(s.op == Onot){
				sourceAST s_a = interpretSourceAST(s.a,idx, bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case STrue:{ return new SFalse();}
					case SFalse:{ return new STrue();}
					default: {return null;}
				}	
			}else{
				return null;
			}
			}
		}
		
		case SPrim2:
		{
			if(bnd <1 ) return null;
			else{
			if(s.op == Oplus){
				int a, b;
				sourceAST s_a = interpretSourceAST(s.a,idx,  bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case SNum:{ a = s_a.val;}
					default:{ return null;}
				}
				sourceAST s_b = interpretSourceAST(s.b,idx,bnd -1);
				if(s_b==null) return null;
				switch(s_b){
					case SNum: {b = s_b.val;}
					default: {return null;}
				}
				return new SNum(val = a+b);
			}else
			if(s.op == Ominus){
				int a, b;
				sourceAST s_a = interpretSourceAST(s.a,idx,  bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case SNum: {a = s_a.val;}
					default: {return null;}
				}
				sourceAST s_b = interpretSourceAST(s.b,idx,bnd-1);
				if(s_b==null) return null;
				switch(s_b){
					case SNum: {b = s_b.val;}
					default: {return null;}
				}
				return new SNum(val = a-b);
			}else
			if(s.op == Oand){
				bit a, b;
				sourceAST s_a = interpretSourceAST(s.a,idx, bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case STrue: {a = 1;}
					case SFalse: {a = 0;}
					default: {return null;}
				}
				sourceAST s_b = interpretSourceAST(s.b,idx, bnd-1);
				if(s_b==null) return null;
				switch(s_b){
					case STrue:{ b = 1;}
					case SFalse:{ b = 0;}
					default: {return null;}
				}
				if (a&&b) return new STrue();
				else return new SFalse();
				
			}else
			if(s.op == Oor){
				bit a, b;
				sourceAST s_a = interpretSourceAST(s.a,idx,  bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case STrue: {a = 1;}
					case SFalse: {a = 0;}
					default: {return null;}
				}
				sourceAST s_b = interpretSourceAST(s.b,idx,  bnd-1);
				if(s_b==null) return null;
				switch(s_b){
					case STrue: {b = 1;}
					case SFalse:{ b = 0;}
					default: {return null;}
				}
				if(a||b) return new STrue();
				else return new SFalse();
				
			}else
			if(s.op == Ogt){
				int a, b;
				sourceAST s_a = interpretSourceAST(s.a,idx, bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case SNum: {a = s_a.val;}
					default: {return null;}
				}
				sourceAST s_b = interpretSourceAST(s.b,idx, bnd-1);
				if(s_b==null) return null;
				switch(s_b){
					case SNum: {b = s_b.val;}
					default: {return null;}
				}
				if(a>b) return new STrue();
				else return new SFalse();
				
			}else
			if(s.op == Olt){
				int a, b;
				sourceAST s_a = interpretSourceAST(s.a,idx,  bnd-1);
				if(s_a==null) return null;
				switch(s_a){
					case SNum:{ a = s_a.val;}
					default: {return null;}
				}
				sourceAST s_b = interpretSourceAST(s.b,idx,bnd-1);
				if(s_b==null) return null;
				switch(s_b){
					case SNum: {b = s_b.val;}
					default: {return null;}
				}
				if(a<b) return new STrue();
				else return new SFalse();
				
			}else{
				return null;	
			}
			}				
		}
		case SBetween:
		{
			
			if(bnd <1 ) return null;
			else{
			int a, b, c;
			sourceAST s_a = interpretSourceAST(s.a,idx,  bnd-1);
			
			if(s_a==null) return null;
			switch(s_a){
				case SNum: {a = s_a.val;}
				default: {return null;}
			}
			sourceAST s_b = interpretSourceAST(s.b,idx,  bnd-1);
			if(s_b==null) return null;
			switch(s_b){
				case SNum:{ b = s_b.val;}
				default: {return null;}
			}
			sourceAST s_c = interpretSourceAST(s.c,idx, bnd-1);
			if(s_c==null) return null;
			switch(s_c){
				case SNum: {c = s_c.val;}
				default: {return null;}
			}
			if(a<b&&b<c) return new STrue();
			else return new SFalse();
			}
			
		}	
		case SIf:
		{
			if(bnd <1 ) return null;
			else{
			sourceAST c  = interpretSourceAST(s.a,idx, bnd-1);
			if(c==null) return null;
			switch(c){
				case STrue:{return interpretSourceAST(s.b,idx, bnd-1);}
				case SFalse: {return interpretSourceAST(s.c,idx,bnd-1);}
				default: {return null;}	
			}
			}
		}
		case SLet:
		{
		if(bnd <1) return null;
		else{
		
		sourceAST s_a = interpretSourceAST(s.a, idx, bnd-1);
		if(s.str<0 || s.str>=size) return null;
		if (idx <= s.str) idx = s.str+1;
		smtStore[s.str] = s_a;
		return interpretSourceAST(s.b, idx, bnd-1);
		}
		}
		default: {return s;}
		
		
		
	}
	
	
}

coreAST[size] cmtStore;
coreAST interpretCoreAST(coreAST s,ref int idx, int bnd,int bnd2){
	assert(bnd >=0);
   if(s == null) return null;
	if(bnd<0 || bnd2 < 0){
		return null;
	}
	switch(s){
		case CVar:
		{
			
			if (s.str >= idx) { return s;}
			
				coreAST val = cmtStore[s.str];
				if(val == null) {  return s;}
				switch(val){
					case CNum: return val;
					case CBool: return val;
					case CVar: return val;
					default: {  return null;}
				
				}
				 
			
		}
		case CAssign:
		{
		
		if(bnd <1 || bnd2<1){  return null;}
		else{
		
		coreAST s_a = interpretCoreAST(s.a, idx,  bnd-1, bnd2-1);
		if(s.str<0 || s.str>= size) { return null;}
		if (idx <= s.str) idx = s.str+1;
		cmtStore[s.str] = s_a;
		return s_a;
		}
		}
		case CPrim1:
		{
			if(bnd <1 || bnd2< 1) return null;
			else{
			if(s.op == Oneg){
				
				coreAST s_a = interpretCoreAST(s.a,idx, bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CNum: {return new CNum(val = (0-s_a.val));}
					default: {return null;}
				}
			}else
			if(s.op == Onot){
				coreAST s_a = interpretCoreAST(s.a,idx, bnd-1, bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CBool:{ return new CBool( val = (!s_a.val));}
					default: {return null;}
				}	
			}else{
				return null;
			}
			}
		}
		
		case CPrim2:
		{
			if(bnd <1 || bnd2 < 1) return null;
			else{
			if(s.op == Oplus){
				int a, b;
				coreAST s_a = interpretCoreAST(s.a,idx, bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CNum: {a = s_a.val;}
					default: {return null;}
				}
				coreAST s_b = interpretCoreAST(s.b,idx, bnd-1,bnd2-1);
				if(s_b==null) return null;
				switch(s_b){
					case CNum: {b = s_b.val;}
					default: {return null;}
				}
				return new CNum(val = a+b);
			}else
			if(s.op == Ominus){
				int a, b;
				coreAST s_a = interpretCoreAST(s.a,idx,bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CNum: {a = s_a.val;}
					default: {return null;}
				}
				coreAST s_b = interpretCoreAST(s.b,idx,bnd-1,bnd2-1);
				if(s_b==null) return null;
				switch(s_b){
					case CNum: {b = s_b.val;}
					default: {return null;}
				}
				return new CNum(val = a-b);
			}else
			if(s.op == Oand){
				bit a, b;
				coreAST s_a = interpretCoreAST(s.a,idx,bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CBool:{ a = s_a.val;}
					default:{ return null;}
				}
				coreAST s_b = interpretCoreAST(s.b,idx,bnd-1,bnd2-1);
				if(s_b==null) return null;
				switch(s_b){
					case CBool:{ b = s_b.val;}
					default: {return null;}
				}
				return new CBool(val = a&&b);
			}else
			if(s.op == Oor){
				bit a, b;
				coreAST s_a = interpretCoreAST(s.a,idx,  bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CBool: {a = s_a.val;}
					default: {return null;}
				}
				coreAST s_b = interpretCoreAST(s.b,idx,bnd-1,bnd2-1);
				if(s_b==null) return null;
				switch(s_b){
					case CBool: {b = s_b.val;}
					default: {return null;}
				}
				return new CBool(val = a||b);
			}else
			if(s.op == Ogt){
				int a, b;
				coreAST s_a = interpretCoreAST(s.a,idx,bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CNum: {a = s_a.val;}
					default: {return null;}
				}
				coreAST s_b = interpretCoreAST(s.b,idx,bnd-1,bnd2-1);
				if(s_b==null) return null;
				switch(s_b){
					case CNum:{ b = s_b.val;}
					default: {return null;}
				}
				return new CBool(val = a>b);
			}else
			if(s.op == Olt){
				int a, b;
				coreAST s_a = interpretCoreAST(s.a,idx,bnd-1,bnd2-1);
				if(s_a==null) return null;
				switch(s_a){
					case CNum: {a = s_a.val;}
					default: {return null;}
				}
				coreAST s_b = interpretCoreAST(s.b,idx,bnd-1,bnd2-1);
				if(s_b==null) return null;
				switch(s_b){
					case CNum:{ b = s_b.val;}
					default: {return null;}
				}
				return new CBool(val = a<b);
			}else{
				return null;	
			}	
			}			
		}
		case CLet:
		{
		
		if(bnd <1 || bnd2<1) return null;
		else{
		
		coreAST s_a = interpretCoreAST(s.a, idx,  bnd-1,bnd2-1);
		if(s.str<0 || s.str>= size) return null;
		if (idx <= s.str) idx = s.str+1;
		cmtStore[s.str] = s_a;
		return interpretCoreAST(s.b, idx,  bnd-1 , bnd2-1);
		}
		}
		case CIf:
		{
			if(bnd <1 || bnd2<1) return null;
			else {
			coreAST c  = interpretCoreAST(s.a,idx,bnd-1,bnd2-1);
			if(c==null) return null;
			switch(c){
				case CBool:
				{
					if (c.val ==1) return interpretCoreAST(s.b,idx, bnd-1,bnd2-1);
					else return interpretCoreAST(s.c,idx, bnd-1,bnd2-1);
						
					
				}
				default: return null;	
			}
			}
		}
		default: return s;
		
		
		
	}
	
	
}
bit equals(sourceAST c1 ,coreAST c2){
	if(c1== null) return true;
	if(c2 == null) return false;
	
	switch(c1){
		
		
		case SNum:
		{
			switch(c2){
				case CNum: return c1.val == c2.val;
				default: return false;
			}
		}
		case STrue:
		{
			switch(c2){
				case CBool:return c2.val==1;
				default: return false;
			}
		}
		case SFalse:
		{
			switch(c2){
				case CBool: return c2.val==0;
				default: return false;
			}
		}
		case SVar:
		{
			switch(c2){
				case CVar: return c1.str == c2.str;
				default: return false;
			}
		}
		
		default: return true;
	}
	
	
}
/*
harness void main3(){
	sourceAST s = new SBetween(a = new SAssign(str = 0, a = new SNum(val =1)),b = new SAssign(str= 0, a = new SPrim2(op = Oplus, a = new SVar(str = 0), b = new SNum(val = 1))),c = new SNum(val = 3));	
	sourceAST c1 = interpretSourceAST(s,0,3);
	
	
	coreAST c2  = desugar(s,4);
	
	for(int i = 0; i < size; i++){
		cmtStore[i] = null;
	}
	int i = 1;
	
	coreAST c3 = interpretCoreAST(c2,0,5,5);
	assert(c3!=null);
	assert(equals(c1,c3));
		
	
}*/

/*
harness void main2(int[40] arr, int sbnd){
	sbnd = sbnd*2;
	int idx =0;
	sourceAST s = produce( arr, idx,3, sbnd);
	
	for(int i = 0; i < size; i++){
		smtStore[i] = null;
	}
	
	sourceAST c1 = interpretSourceAST(s,0,3);
	
	if(c1 != null){
		coreAST c2  = desugar(s,4);
		
		for(int i = 0; i < size; i++){
			cmtStore[i] = null;
		}
		int i = 1;
		while(sbnd/2 >=1) {sbnd = sbnd/2; i++;}
		coreAST c3 = interpretCoreAST(c2,0,4,i+1);
		assert(c3!=null);
		assert(equals(c1,c3));
		
	}
	
}
*/
/*

harness void main1( int[50] arr, int sbnd){
	
	int idx =0;
	sourceAST s = produce( arr, idx, 3, sbnd);
	
	for(int i = 0; i < size; i++){
		smtStore[i] = null;
	}
	
	sourceAST c1 = interpretSourceAST(s,0,3);
	
	if(c1 != null){
		coreAST c2  = desugar(s,4);
		
		for(int i = 0; i < size; i++){
			cmtStore[i] = null;
		}
		int i = 1;
		while(sbnd/2 >=1) {sbnd = sbnd/2; i++;}
		coreAST c3 = interpretCoreAST(c2,0,5,i+2);
		assert(c3!=null);
		assert(equals(c1,c3));
		
	
	}
}
*/
harness void main0( int[30] arr, int sbnd){
	
	int idx =0;
	sourceAST s = produce( arr, idx, 1, sbnd);
	
	for(int i = 0; i < size; i++){
		smtStore[i] = null;
	}
	int vv = 0;
	sourceAST c1 = interpretSourceAST(s,vv,1);
	
	if(c1 != null){
		coreAST c2  = desugar(s,2);
		
		for(int i = 0; i < size; i++){
			cmtStore[i] = null;
		}
		int i =1;
		while(sbnd/2 >=1) {sbnd = sbnd/2; i++;}
		int v = 0;
		coreAST c3 = interpretCoreAST(c2,v,3,i+1);
		assert(c3!=null);
		assert(equals(c1,c3));
		
	
	}
}

