int N = 4;

bit[N] transpose(bit[N] input){
	bit[N] output=0;
	for(int i=0; i<N; ++i){
		output[i] = input[i];
	}
	return output;
}


bit[N] tiledTranspose(bit[N] input)implements transpose{
	bit[N] output=0;
	bit[N] check = 0;
	int i=0;
	int it = ??;
	repeat(??){
		int j=0;
		repeat(it){
		    assert (i+j) < N;
			output[i+j] = input[i+j];
			assert !check[i+j];
			check[i+j] = 1;
			j=j+1;
		}
		i = i+2;
	}
	return output;
}