//Correct
struct Tree{}
struct Leaf extends Tree{}
struct Branch extends Tree{}

harness void test(){	
Branch branch = new Branch();
int x =   sum(branch);
}

int sum(Tree t){
	int x;		
    switch(t){
        case Leaf: 
            
            {
                        x =1;
            }                     
      
            
        case Branch:
			{
            x=2;
		}
    }
    return x;
}