
package A{
int x = 92;
int y = ??;
int z = 3;

generator int gety(){
    return y;
}

@Native("{ assert(t==10); } ")
int checky(int t);
int tt = ??;

int[tt] foo(int[tt] x){
    return x;
}

harness void main1(){
    assert gety() == 10;
    checky(gety());
    {
        int yy;
        yy = ??;
        yy = yy + 90;
        assert yy == 95;
    }
    checky(gety());
    int[3] v = foo({1,2,3});
}

}