/*
This is to test function inlining, and the handling of cycles in tests.
*/


int foo(int x, int y){    
    return (x + y)/2;    
}

int id(int t){
    return 0;    
}

harness void main1(int x, int y){
    int t = 0;
    if(x < y){
        t = foo(x, y);
        if(x>1){
            t = t/2;
        }
    }
    if(t < 3){
        t = id(t)+t;
        t += foo(x, y);
    }
    if(t<5){
        t = t + foo(x,y);
        if(t > 3){
            t = foo(x,y);
        }
    }
    assert t <= 10*(x+y);
}
