struct ID {int i;}

adt dstAST{
    VarD { ID name;}
    AbsD { dstAST var; ID a;}    
}

dstAST xx;

ID foo(int n){
    if(n>0){
        ID t = foo(n-1);
        ID p = new ID(i= t.i + 1);
        xx = new AbsD(var=xx, a=p);
        return p;
    }else{
        ID q = new ID(i=0);
        xx = new VarD(name = q);
        return q;
    }
}

ID moo(dstAST u){
    switch(u){
    case VarD: {  ID i = u.name; return new ID(i=i.i); }
    case AbsD: {  return moo(u.var); }
    }    
}


harness void main(int n){
    assume n < 5;
    ID t = foo(n);
    moo(xx);
    ID q;
    if(??){ q = new ID(i=n+??); }
    assert q.i == t.i;
}
    
    
