bit[5] spec(bit[5] in){    
    in[1::2] = in[0::2];    
    return in;
}

bit[5] sk(bit[5] in) implements spec{
    bit[2] t = in[0::2];
    in[1::2] = t;
    bit[3] x = 0;
    x[1::2] = {1,1};
    int t0 = (int)x;    
    assert x[0] == 0 && x[1] == 1 && x[2] == 1;
    int q = ??;
    assert {1,2,3,4,5,6,7,8}[t0] == ??;    
    
    int[3] z = {1,2,3};
    int a = ??;
    int b = ??;
    z[{1,2}[a]] = 3;
    z[0] = {4,5,6}[b];
    assert z[0] == 4 && z[1] ==3; 
    z[{0,1}[a]::2] = {0,1,2,3,4,5,6}[b::2];
    assert z[0] == 0 && z[1] == 1; 
        
    return in;
}