/**
 * Usage example:
 * CHOICE_INT(x1)
 * mysynthfunc() { choice(x1); }
 */

#pragma once
#define CHOICE_INT(VAR) \
    int[100] choiceValues_ ## VAR = ??; \
    int choiceCtr_ ## VAR = 0; \
    int choice_ ## VAR() { \
        int oldctr = choiceCtr_ ## VAR; \
        choiceCtr_ ## VAR++; \
        return choiceValues_ ## VAR[oldctr]; \
    } \

#define choice(var) (choice_ ## var())
#define reset(var) { choiceCtr_ ## var = 0; }
#define setChoiceArr(var, arr, N) \
    for (int a = 0; a < N; a++) { arr[a] = choice(var); }

CHOICE_INT(x1)

harness void main() {
    assert choice(x1) == 1;
    assert choice(x1) == 0;

    int[6] choiceArr;
    setChoiceArr(x1, choiceArr, 6)
    assert choiceArr[0] == 1;
    assert choiceArr[1] == 3;
}
