int NNODES = 3;

struct Set {
    Node head;
    Node tail;
}

struct Node {
    int key;
    Node next;
}


generator Set newSet (int negInf, int posInf) { /* automatically rewritten */
    Set S = new Set ();
    S.tail = newNode (posInf, null);
    S.head = newNode (negInf, S.tail);
    return S;
}

generator Node newNode (int key, Node next) { /* automatically rewritten */
    Node n = new Node ();
    n.key = key;
    n.next = next;
    return n;
}


void VOID(int s){

}

void main_fun(int s) implements VOID{
	Set S = newSet(-1, 10);
	assert S.head.key == -1;
}



