pragma options "--bnd-unroll-amnt 32";

harness void main(int n){
    int[n] xx;
    for(int i=0; i<n; ++i){
        int[i] ar;
        for(int j=0; j<i; ++j){
            ar[j] = j;
        }
        if(i>0){
            assert ar[i-1]==i-1;
        }
    }
    
    for(int i=0; i<=n; ++i){
        int[i] ar;
        for(int j=0; j<i; ++j){
            ar[j] = j;
        }
        if(i>0){
            assert ar[i-1]==i-1;
        }
    }
    
    for(int k=0; k<=n; k+= 1){
        int[k] ar;
        for(int j=0; j<k; ++j){
            ar[j] = k;
        }
        if(k>0){
            assert ar[k-1]==k;
        }
    }
    
    for(int k=0; k<=n; k= k + 1){
        assert k <= n;
    }            
}