int N = 8;
int NULL = -1;
int  NTHREADS = 2;
int MEMSIZE = 8;

bit one(bit[N] in){
	return 1;
}


generator bit checker(int[MEMSIZE] mem, int tail){ /* automatically rewritten */
	int val = mem[0];
	int ptr = mem[1];
	int lastPtr = NULL;	
	int checksum = 0;
	int cnt = 0;
	repeat(4){
	  if(ptr != NULL){	
	  	cnt = cnt + 1;
	  	val = mem[ptr];
	  	assert val == 4 || val == 5 || val == 6;
	  	checksum = checksum + val;	  	
	  	lastPtr = ptr;
	  	ptr = mem[ptr+1];
	  }
	}
	return ((mem[2] == 4 && mem[4] == 5 && mem[6] == 6 ) ||
   			( mem[2] == 4 && mem[4] == 6 && mem[6] == 5 ))&& cnt == ??;	
}


bit parallel1(bit[N] in) implements one{
  int[NTHREADS] pc = 0;    
  int malloc = 4;
  int tail = 2;  
  int[MEMSIZE] mem = 0;
  mem[0] = -1;
  mem[1] = 2;
  mem[2] = 4;
  mem[3] = NULL;
  
  int [NTHREADS] data = {5, 6};
  int[NTHREADS] ne= 0;
  int[NTHREADS] oldTail = 0;  
  
  
  
  for(int t=0; t < N; ++t){
  	bit runThr0 = (in[t] && pc[1] < 4 ) || pc[0] >= 4 ; 
  	{
  		if(pc[runThr0] == 0){
  		  ne[runThr0] = malloc;	
  		  malloc = malloc + 2;  		  
  		}
  		if(pc[runThr0] == 1){
  		  mem[ne[runThr0]] = data[runThr0];
  		  mem[ne[runThr0]+1] = NULL;
  		}  		
  		if(pc[runThr0] == 2){
  		  oldTail[runThr0] = tail;
  		  tail = ne[runThr0];	
  		}
  		if(pc[runThr0] == 3){
  		  mem[oldTail[runThr0]+1] = ne[runThr0];	
  		}
  		pc[runThr0] = pc[runThr0] + 1;
  	}
  }

   return checker(mem, tail);
} 