pragma options "--bnd-inbits 4";

stencil int[N] test8(int N, int[N] in, int a, int b){
  int[N] out;
  for(int i=0; i<N; ++i){
  	if(i>0 && i<N-1) out[i] = a*in[i-1] + b*in[i+1];
  	else out[i] = 0;
  }
  return out;
}

stencil int[N] testSK8(int N, int[N] in, int a, int b) implements test8 {
  int[N] out = 0;
  for(int i=??; i<(N-??); ++i){
  	out[i] = a*in[i-1] + b*in[i+1];  	
  }
  return out;
}
