//Tests for ADT
struct Tree{}
struct Leaf extends Tree{}    
struct Branch extends Tree{}

harness void test(){
	Branch branch = new Branch();
	int x =   sum(branch);
}

int sum(Tree t){
	
		
    switch(t){
        case Leaf:           
            {     
            	//some error araises when case block is empty in flattenStmtBlock      
            }    
        case Branch:
			{           
            return 2;
			}	
			
    }
    return 1;
    
}