pragma options "--bnd-unroll-amnt 16 --bnd-inbits 4";

int[N] foo([int N], int[N] in);

int[N] check(int N, int[N] input){
    if(N==5){
        return foo(input);
    }else{
        return 0;
    }
}

int[N] other(int N, int[N] input) implements check{
    if(N==5){
        int[N] x;
        for(int i=0; i<N; ++i){
            x[i] = input[i];
        }
        return foo(x);
    }else{
        return 0;
    }
}