pragma options "--bnd-inbits 4 --be:showDAG --beopt:-bndwrand 50 --bnd-unroll-amnt 2  --bnd-mbits 3";


int mooReal(int i, int h){
    int rv;
    minrepeat{
        if(??){rv = max({| (i| h| rv| ??)+?? |}, {| (i| h| rv| ??)+?? |}); }
        else{
            if(??){ rv = min({| (i| h| rv| ??)+?? |}, {| (i| h| rv| ??)+?? |});}
            else{ rv = {| ((i| h| rv| ??)+??) (+ | -) ((i| h| rv| ??)+??) |};  }
        }
    }
    return rv;
}

harness void checkMooReal(int i, int h){
    int rv = mooReal(i, h);
    if(i==7 && h > 12){
        assert rv > 10;
        assert rv >= i;
        assert rv <=max(h, i);
    }    
}

@Native("{ mooReal(i, h, _out); }")
int moo(int i, int h);

int max(int i, int j){ return i>j?i:j; }
int min(int i, int j){ return i>j?j:i; }

model int foo(int i, int h){
    int rv = moo(i, h);
    if(i==7 && h > 12){
        assert rv > 10;
        assert rv >= i;
        assert rv <=max(h, i);
    }
    return rv;
}



harness void main(int i, int j){
 
    int q = ??;
    
    if(i == 7){
        // assert q+3 < (i+5)+ (3-i);
        assert q < (i+5)+ (-i);
    }
    
    {
        foo(i, q);
    }        
}