pragma options "--bnd-inbits 2 --bnd-unroll-amnt 16";

harness void main(int N, int M, int [N][M] x){
    int[N][N] rv = square(N,M,x);    
}

int[N][N] square(int N, int M, int [N][M] x){
    int[{|N|M|}][{|N|M|}] xx;
    for(int i=0; i<{|N | M |}; ++i){
        for(int j=0; j<{|N | M |};++j){
            xx[i][j] = x[j][i];            
        }           
    }
    int[N][N] out;
    for(int i=0; i<{|N | M |}; ++i){
        for(int j=0; j<{|N | M |};++j){
            for(int k=0; k<{|N | M |}; ++k){
                out[{|i|j|k|}][{|i|j|k|}] += xx[{|i|j|k|}][{|i|j|k|}] * x[{|i|j|k|}][{|i|j|k|}];            
            }
        }           
    }
    return out;
}