pragma options "--bnd-inbits 3";

int[N] test5(int N, int[N] in){
  int[N] out;
  for(int i=0; i<N; ++i){
  	if(i>0 && i<N-1) out[i] = in[i-1] + in[i+1];
  	else out[i] = 0;
  }
  return out;
}


int[N] testSK5(int N, int[N] in) implements test5{
  int[N] out;
  int t0;
  if(N>??){
      t0  = in[??];
      int t1;
      if(N>??){
          t1 = in[??];
          out[??] = 0;
          out[N-??] = 0;
          for(int i=??; i<N-??; ++i){
            int t2;
            t2 = in[i+1]; 
          	out[i] = t0 + t2;
          	if(??){
        	  	t0 = t1;
        	  	t1 = t2;
          	}else{
        	  	t1 = t2;
          	  	t0 = t1;
          	}
          }
      }
  }
  return out;
}
