pragma options "--debug-show-dag   ";

struct Q{
    int u;
    int v;
}


struct F{
    int x;
    int y;
    Q q;
}

@Native("{ assert (v1==v2); }")
void secretAssertEquals(int v1, int v2);

void foo(ref |F| x){
    x.y = 22;
}

harness void moo(){
    F x = new F();
    |F| a = |F|(x=5, y=7);
    
    |F| b = a;
    foo(a);
    assert b.x == 5;
    assert a.y == 22;
    secretAssertEquals(b.x , 5);
}