
struct Point{
    int x;
    int y;
}

|Point| p3 = |Point|(x=5, y=3);

harness void aaa(int i, int j){
    |Point| p1 = |Point|(x=5, y=3);
    Point p = new Point(x=3, y=2);
    
    foo(p);
    foo(p3);
    assert p.x == 4;
}


void foo(ref |Point| p ){
    ++p.x;
}

harness void main(int i, int j){
    |Point| p1 = |Point|(x=5, y=3);
    Point p2 = new Point(x=3, y=2);
    
    foo(p2);
    
    assert p2.x == 4;
}