pragma options "--bnd-inbits 2 --bnd-inline-amnt 1";

// test PartialEvaluator: correctly handle StmtSwitch with only one case

struct Opr {}
struct A extends Opr {}

generator void bad(Opr op) {
	switch(op) {
	case A:
		assert 0 : "#BADBAD#";
	}
}

harness void f() {
	Opr a = new A();
	
	if (??) {
		bad(a);
	}
	
	int x = 0;
	switch(a) {
	case A:
		x = 1;
	}
	
	int y = 0;
	switch(a) {
	default:
		y = 2;
	}
	
	assert x == 1 && y == 2;
}
