adt Foo{
    A{}
    B{}
}

generator void forall<T>([int n], fun f, T[n] x){
    for(int i=0; i<n; ++i){
        f(x[i]);
    }
}

harness void main(){
    Foo x = new A();
    Foo y = new B();
    int sum=0;
    generator void tt(Foo f){
        
    }
    generator void add(int t){
        sum += t;
    }
    forall(add, {1,2,3,4,5});
    assert sum == ??;    
    forall(tt, {x,y});
    sum = 0;
    forall( (u) -> forall(add, u),  { {1,2,0} , {3,4,5} } );
    assert sum == 15;    
}

