pragma options "--bnd-intbits 6";
int N = 4;

generator bit[N] intToBit(int v){ /* automatically rewritten */
	bit[N] output;
	for(int i=0; i<N; ++i){
		output[i] = (v % 2) > 0;
		v = v/2;
	}
	return output;
}


bit[4] reverseSketch(bit[4] in) implements reverse {	
	bit[4] tmp = ??;
	return in + tmp;
	
}

bit[4] reverse (bit[4] in) {
	int[16] tmp = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2};
	return intToBit( tmp[(int)in] );
}