int moo(int in, ref int tmp){
    tmp = in;
    int q = ??;
    assert q == 15;
    if(in+(??-in) != 15){
        return moo(in, tmp);
    }else{
        return in;
    }
}


int foo(int in){
    int x = in;
    if(in > 5){        
        in = moo(in, x);
    }
    return in;
}

harness void main(int in){
    if(in > 5){
    if(foo(in)>0){
        if(foo(in)<10){
            foo(in);
        }
    }
    }    
}