int N = 2;
// x <= y
generator bit leq(bit x, bit y){ /* automatically rewritten */
	return !x || y;
}
bit[N] sort(bit[N] input){
	bit[N] output=0;
	bit[N] done = 0;
	int k=0;
	for(int i=0; i<N; ++i){
		bit cur = 1;
		for(int j=0; j<N; ++j){
			if( leq(input[j], cur) && !done[j]){
				k = j;
				cur = input[j];
			}
		}
		output[i] = cur;
		done[k] = 1;
	}
	return output;
}


bit[N] mergeSort(bit[N] input)implements sort{
	bit[N] output=1;
	if( input[0] && input[1] ){ output[0] = 1; output[1] = 1;   };
	if( !input[0] && input[1] ){ output[0] = 0; output[1] = 1;   };
	if( input[0] && !input[1] ){ output[0] = 0; output[1] = 1;   };
	if( !input[0] && !input[1] ){ output[0] = 0; output[1] = 0;   };
	return output;
}


