

struct A{}
struct B extends A{ A x;}
struct C extends A{ A y;}
struct D extends A{ A x; A z;}


bit checkEq(A a, A b){
	if(a==null && b == null) return true;
	switch(a){
		case B :{ B bb = (B) b; return checkEq(a.x, bb.x); }
		case C :{ C bb = (C) b; return checkEq(a.y, bb.y); }
		case D :{ D bb = (D) b; return checkEq(a.x, bb.x) && checkEq(a.z, bb.z); }
	}
}


harness void main(){

	generator A newGen(int bnd){
		if(bnd <= 0){ return null; }
		return new ??(x = newGen(bnd-1), y = newGen(bnd -1), z = newGen(bnd -1));
	}

	A a = newGen(4);
	A b = newGen(4);
	
	assert(checkEq(a, b));
	

}