int N = 4;

// x <= y
generator bit leq(bit x, bit y){ /* automatically rewritten */
	return !x || y;
}
bit[N] sort(bit[N] input){
	bit[N] output=0;
	bit[N] done = 0;
	int k=0;
	for(int i=0; i<N; ++i){
		bit cur = 1;
		for(int j=0; j<N; ++j){
			if( leq(input[j], cur) && !done[j]){
				k = j;
				cur = input[j];
			}
		}
		output[i] = cur;
		done[k] = 1;
	}
	return output;
}


bit[N] MergeSort(bit[N] input)implements sort{
	bit [N] output;
	output = (input<<??) {|} (input>>??);
	assert output[0] == input[2] && 
		 	output[1] == input[3] && 
		  	output[2] == input[0] && 
		   	output[3] == input[1] ;
	return sort(output);
}

