int N = 4;

generator bit[N] intToBit(int v){ /* automatically rewritten */
	bit[N] output;
	for(int i=0; i<N; ++i){
		output[i] = (v % 2) > 0;
		v = v/2;
	}
	return output;
}


bit[4] reverseSketch(bit[8] in) implements reverse {	
	bit[4] out=0;
	bit[4*16] Ta = ??;
	bit[4*16] Tb = ??;
	bit [4] a=0;
	bit [4] b=0;
	assert !Ta[0] && Ta[1] && !Ta[2] && !Ta[3];
	for(int i=0; i<4; ++i){
		a[i] = in[i];
		b[i] = in[4+i];
	}
	int inva = (int) a;
	int invb = (int) b;
	
	for(int i=0; i<4; ++i){
		out[i] = Ta[inva*4 + i] ^ Tb[invb*4 + i];
	}
	return out;
	
}

bit[4] reverse (bit[8] in) {
	int[16] tmp = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2};
	bit [4] a=0;
	bit [4] b=0;
	for(int i=0; i<4; ++i){
		a[i] = in[i];
		b[i] = in[4+i];
	}
	bit [4] out = intToBit( tmp[(int)a] );
	return  (out<<1) ^ intToBit( tmp[(int)b] );
}