pragma options "--bnd-inline-amnt 3 --bnd-unroll-amnt 16 --bnd-arr-size 16";
pragma options "--bnd-inbits 4";



stencil bit[N][N] tiledTranspose(int N, int P, bit[N][N] input)implements transpose{
    if(N<1 || P < 1 || N % P != 0){ return 0; }
    bit[N][N] output=0;
    
    //int p=0;
    for(int p=0; p<P; ++p){
        for(int i={| ((N/P)|p|N) * ((N/P)|p|N) |}; i<(N/P)*(p+1); ++i){
            for(int j=0; j<N; ++j){
                output[i][j] = input[j][i];
            }
        }
    }
    return output;
}


 stencil bit[N][N] transpose(int N, int P, bit[N][N] input){
    if(N<1 || P < 1 || N % P != 0 ){ return 0; }
    bit[N][N] output=0;
    for(int i=0; i<N; ++i){
        for(int j=0; j<N; ++j){
            output[i][j] = input[j][i];
        }
    }
    return output;
}

