struct Foo{
    
    int x;
}
int spec(int x){
    Foo f = new Foo();
    f.x = x;
    return f.x;
}

int sketch(int x)implements spec{
    Foo f = new Foo();
    f.x = spec(x);
    if(??){
    	//Chosing this branch can lead to an infinite loop, but the synthesizer
    	//could still pick this branch because it tries to solve the sketch under
    	//the assumption that replacing sketch with spec is always ok, without 
    	//checking for termination.
        return sketch(f.x);
    }else{
        return f.x;
    }
}