


stencil float[N][N] test0(int N, float[N][N] a){
  float[N][N] out=0.0;
  for(int i=0; i<N; ++i){
    for(int j=0; j<i; ++j){
        out[i][j] = a[i][j];
    }
  }
  return out;
}


generator int hole(int i, int N){ /* automatically rewritten */
    int rv = 0;    
    if(??){
        rv = N;
    }else{
        rv = i;
    }    
    return rv;  
}




stencil float[N][N] testSK0(int N, float[N][N] a) implements test0 {
  float[N][N] out=0.0;
  for(int i=0; i<hole(0, N); ++i){
    for(int j=0; j<hole(i, N); ++j){
        out[i][j] = a[i][j];
    }
  }
  return out;
}