pragma options "--bnd-unroll-amnt 5";


bit StrEquals(int n1, char[n1] c1, int n2, char[n2] c2){
    for(int i=0; i<n1; ++i){
        if(i>= n2){
            return false;
        }
        if(c1[i] == 0){
            return c2[i] == 0;
        }
        if(c2[i] != c1[i]){
            return false;
        }
    }   
    return true;
}

bit foo (int [4] a){
    int[3] ab = {3, 7, 0};
    return StrEquals(4, a,3, ab);
}

bit Sk(int[4] a) implements foo {
    
    int[4] tmp = ??;
    return StrEquals(??, a , ??, tmp);
}