pragma options "--be:showDAG";

int moo(int i);

model int foo(int i, int h){
    //This foo should not be allowed, because for some values of h, 
    // no function can satisfy the model.
    int rv = moo(i);
    if(i==7){
        assert rv > 10;
        assert rv >= i;
        assert rv <h;
    }
    return rv;
}



harness void main(int i, int j){
 
    int q = ??;
    
    if(i == 7){
        // assert q+3 < (i+5)+ (3-i);
        assert q < (i+5)+ (-i);
    }
    
    {
        foo(i, q);
    }        
}