pragma options "--bnd-unroll-amnt 16 --bnd-arr-size 16";
pragma options "--bnd-inbits 4";
// 5 i 1
// 5 i 2
stencil bit[N] test(int N, bit[N] in){
    bit[N] out;
    bit tmp= in[0];
    for(int i=1; i<N; ++i){        
        out[i] = tmp;
        bit x = in[i];
        tmp = x;
    } 
    return out;
}

stencil bit[N] sk(int N, bit[N] in) implements test{
    bit[N] out;    
    for(int i=??; i<N-??; ++i){
        out[i] = in[i+??-1] ;    
    }   
    return out;
}