
pragma options "--debug-show-dag";

struct T{
    int x;
    int y;
    int z;
    Foo f;
}

adt Foo{
    Car{int x; int y; }
    Dog{int z; int u; }
    Tv{ T t; Foo f;}
}


harness void main(int x){
    Foo f = new Car(x=4);
    Foo g = new Car(x=??, y=??);
    T t = new T(x=??, y=??, z=??, f = f);
    T u = new T(x=??, y=7, z=2, f=g);
    Foo h = new Tv(t=t);
    
   assert f != null;
   assert !(f==null);
    
   Tv tv = (Tv) h;
   assert tv.f == null;
    
}