
generator void rep(int n, fun f){
    if(n>0){
        f();
        rep(n-1, f);
    }    
}


bit[16] reverseSketch(bit[16] in) implements reverse {

    bit[16]  t = in;    
    int s = 1;
    generator void tmp(){
        bit[16] tmp1 = (t << s);
        bit[16] tmp2 = (t >> s);
        t = tmp1 {|} tmp2;
        s = s*??;
    }
    rep(??, tmp);
    return t;
}


bit[16] reverse (bit[16] in) {
    bit [16] out;
    for (int i = 0; i < 16; i++) {
        out[i] = in[15 - i];
    }
    return out;
}
