pragma options "-ufunSymmetry --synth ABC --verif ABC --seed 10 --cex --inbits 1 --cbits 1 --unrollamnt 4 --heapsize 1 --arrayOOBPolicy assertions";
pragma options "--intbits 6";
#define MODEL_INT 1
#define N 4

//#include "model.skh"




#ifdef MODEL_BIT
#define T bit
T mul(T x, T y) { return x & y; }
#endif

#ifdef MODEL_INT 
#define T int
generator T mul(T x, T y) { return x * y; } /* automatically rewritten */
#endif

#ifdef MODEL_UFUN1
#define T int
static T mul(T x, T y) {
	if (x == 0) return 0;  
	else return ufun_ii(x,y);
}
T ufun_ii(T x, T y);
#endif

#ifdef MODEL_UFUN2
#define T int
static T mul(T x, T y) {
	if (x == 0 || y == 0) return 0;  
	else return ufun_ii(x,y);
}
T ufun_ii(T x, T y);
#endif


//%%%%%%	%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

#define Var ({|i|j|n|0|}+??)
//#define Var ({|i|j|0|0|})

/* Index-type hole composed of array exprs */
#define IArr ((??) ? Var : ((??) ? A.	R[Var] : A.C[Var]))

/* Value-type hole composed of array exprs */
#define VArr ((??) ? A.V[IArr] : x[IArr])  

#define Loop(iv,S,E) for(iv = S; iv < E; iv++) 

T[N] SpMV_Sketch(CSR A, T[N] x, int n) { /* automatically rewritten */
	T[N] y=0;
	int i, j;
	int which = ??;
//	i = 0;
//	j = 0;
	Loop(i, IArr, IArr) {
//	for (int i = 0; i < n; i++) {
		Loop(j,IArr,IArr) {
//		for (int j = A.R[i]; j < A.R[i+1]; j++) {
		
//		for (int idx = Arr; idx < Arr; idx++) {
//			y[r] += mul(A.V[idx],x[A.C[idx]]);
//			int xi = ((??) ? A.C[Var] : Var);
//			y[Var] += mul(VArr,VArr);
//			y[i] += mul(A.V[j],x[A.C[j]]);
			
			y[Var] += mul(A.V[IArr],x[A.C[IArr]]);
		}
	} 
	return y;	
}


//
// computes y = Ax on sparse A and dense x and y.
// 
T[N] SpMV(CSR A, T[N] x, int n) { /* automatically rewritten */
	T[N] y;
	
	for (int r = 0; r < n; r++) {
		y[r] = 0;
		for (int idx = A.R[r]; idx < A.R[r+1]; idx++) {
			y[r] += mul(A.V[idx],x[A.C[idx]]);  
		}
	} 
	return y;	
}

//%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%











//int[N][N] sd(int[N][N] a) implements identity {
//	return desparsify(sparsify(a));
//}
T[N] main(T[N][N] A, T[N] x) implements DeMV {
	return SpMV_Sketch(sparsify(A), x, N);
//	return SpMV(sparsify(A), x, N);
}
//int harness () { // implements one {
//	T[N*N] a = {1,0,0,1};
//	T[N] x ={1,1};
//	T[N][N] dA;
//	int k = 0;
//	for (int i = 0; i < N; i++) 
//		for (int j = 0; j < N; j++) 
//			dA[i][j] = a[k++];
//			
//	CSR sA = sparsify(dA);
//	T[N] y = SpMV(sA,x,N);
//	T[N] yy = DeMV(dA,x);
//	assert y[0] == yy[0];
//	//assert y[1] == yy[1];
//	//assert y[2] == yy[2];
//	return 1;
//}  
generator int one () { return 1; } /* automatically rewritten */
generator int[N][N] identity(int[N][N] A) { return A; } /* automatically rewritten */

struct CSR {
	T[N*N] V;
	int[N*N] C;
	int[N+1] R;
}

CSR sparsify(T[N][N] a) { /* automatically rewritten */
	CSR sm = new CSR();
	
	int idx = 0;
	sm.R[0]=idx;
	
	for (int r = 0; r < N; r++) {
		sm.R[r] = idx;
		for (int c = 0; c < N; c++) {
			if (a[r][c] != 0) {
				sm.V[idx] = a[r][c];
				sm.C[idx] = c;
				idx++;  
			}
		}
	}
	sm.R[N] = idx;
	return sm;
}

int[N][N] desparsify(CSR sm) { /* automatically rewritten */
	T[N][N] a = 0;
	for (int r = 0; r < N; r++) {
		for (int idx = sm.R[r]; idx < sm.R[r+1]; idx++) {
			a[r][sm.C[idx]] = sm.V[idx];
		}
	}
	return a;
}



//
// computes y = Ax on dense A, x, and y.
// 
T[N] DeMV(T[N][N] A, T[N] x) {
	T[N] y = 0;
	
	for (int r = 0; r < N; r++) {
		y[r] = 0;
		for (int c = 0; c < N; c++) {
			y[r] += mul(A[r][c],x[c]);  
		}
	} 
	return y;	
}

