// $ANTLR 2.7.7 (20060906): "StreamItParserFE.g" -> "StreamItParserFE.java"$

package sketch.compiler.parser;

import java.io.DataInputStream;
import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.Map;
import java.util.HashMap;

import sketch.compiler.Directive;
import sketch.compiler.ast.core.FEContext;
import sketch.compiler.ast.core.FieldDecl;
import sketch.compiler.ast.core.Function;
import sketch.compiler.ast.core.Parameter;
import sketch.compiler.ast.core.Program;
import sketch.compiler.ast.core.Annotation;
import sketch.compiler.ast.core.NameResolver;
import sketch.util.datastructures.HashmapList;
import sketch.compiler.ast.core.exprs.ExprStar.Kind;

import sketch.compiler.ast.core.Package;


import sketch.compiler.ast.core.exprs.*;
import sketch.compiler.ast.core.exprs.regens.*;
import sketch.compiler.ast.core.stmts.*;
import sketch.compiler.ast.core.typs.*;
import sketch.compiler.ast.cuda.exprs.*;
import sketch.compiler.ast.cuda.stmts.*;
import sketch.compiler.ast.cuda.typs.*;

import sketch.compiler.ast.promela.stmts.StmtFork;
import sketch.compiler.main.cmdline.SketchOptions;

import sketch.compiler.ast.spmd.stmts.StmtSpmdfork;

import static sketch.util.DebugOut.assertFalse;

public interface StreamItParserFETokenTypes {
	int EOF = 1;
	int NULL_TREE_LOOKAHEAD = 3;
	int TK_atomic = 4;
	int TK_fork = 5;
	int TK_insert = 6;
	int TK_into = 7;
	int TK_loop = 8;
	int TK_repeat = 9;
	int TK_minrepeat = 10;
	int TK_new = 11;
	int TK_null = 12;
	int TK_reorder = 13;
	int TK_assume = 14;
	int TK_hassert = 15;
	int TK_boolean = 16;
	int TK_float = 17;
	int TK_bit = 18;
	int TK_int = 19;
	int TK_void = 20;
	int TK_double = 21;
	int TK_fun = 22;
	int TK_char = 23;
	int TK_struct = 24;
	int TK_ref = 25;
	int TK_adt = 26;
	int TK_if = 27;
	int TK_else = 28;
	int TK_while = 29;
	int TK_for = 30;
	int TK_switch = 31;
	int TK_case = 32;
	int TK_repeat_case = 33;
	int TK_default = 34;
	int TK_break = 35;
	int TK_do = 36;
	int TK_continue = 37;
	int TK_return = 38;
	int TK_true = 39;
	int TK_false = 40;
	int TK_parfor = 41;
	int TK_until = 42;
	int TK_by = 43;
	int TK_implements = 44;
	int TK_assert = 45;
	int TK_assert_max = 46;
	int TK_h_assert = 47;
	int TK_generator = 48;
	int TK_harness = 49;
	int TK_model = 50;
	int TK_global = 51;
	int TK_serial = 52;
	int TK_spmdfork = 53;
	int TK_stencil = 54;
	int TK_include = 55;
	int TK_pragma = 56;
	int TK_package = 57;
	int TK_extends = 58;
	int TK_let = 59;
	int TK_precond = 60;
	int TK_cons = 61;
	int TK_fields = 62;
	int TK_cases = 63;
	int ARROW = 64;
	int LARROW = 65;
	int WS = 66;
	int LINERESET = 67;
	int SL_COMMENT = 68;
	int ML_COMMENT = 69;
	int LPAREN = 70;
	int RPAREN = 71;
	int LCURLY = 72;
	int RCURLY = 73;
	int LSQUARE = 74;
	int RSQUARE = 75;
	int PLUS = 76;
	int PLUS_EQUALS = 77;
	int INCREMENT = 78;
	int MINUS = 79;
	int MINUS_EQUALS = 80;
	int DECREMENT = 81;
	int STAR = 82;
	int STAR_EQUALS = 83;
	int DIV = 84;
	int DIV_EQUALS = 85;
	int MOD = 86;
	int LOGIC_AND = 87;
	int LOGIC_OR = 88;
	int BITWISE_AND = 89;
	int BITWISE_OR = 90;
	int BITWISE_XOR = 91;
	int ASSIGN = 92;
	int DEF_ASSIGN = 93;
	int TRIPLE_EQUAL = 94;
	int EQUAL = 95;
	int NOT_EQUAL = 96;
	int LESS_THAN = 97;
	int LESS_EQUAL = 98;
	int MORE_THAN = 99;
	int MORE_EQUAL = 100;
	int QUESTION = 101;
	int COLON = 102;
	int SEMI = 103;
	int COMMA = 104;
	int DOT = 105;
	int BANG = 106;
	int LSHIFT = 107;
	int RSHIFT = 108;
	int NDVAL = 109;
	int NDVAL2 = 110;
	int SELECT = 111;
	int NDANGELIC = 112;
	int AT = 113;
	int BACKSLASH = 114;
	int LESS_COLON = 115;
	int DOLLAR = 116;
	int DOTASSIGN = 117;
	int DOTPLUS = 118;
	int DOTMINUS = 119;
	int DOTTIMES = 120;
	int DOTDIV = 121;
	int DOTMOD = 122;
	int DOTLT = 123;
	int DOTGT = 124;
	int DOTLTE = 125;
	int DOTGTE = 126;
	int REGEN = 127;
	int CHAR_LITERAL = 128;
	int STRING_LITERAL = 129;
	int ESC = 130;
	int DIGIT = 131;
	int HQUAN = 132;
	int NUMBER = 133;
	int ID = 134;
	int TK_device = 135;
	int TK_library = 136;
	int TK_printfcn = 137;
}
